# Generated by Django 3.0.2 on 2020-02-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=350)),
                ('event', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
