# Generated by Django 3.0.2 on 2020-02-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsmain', '0002_auto_20200212_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsertImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='regist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='regist',
            name='event',
        ),
        migrations.RemoveField(
            model_name='regist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='regist',
            name='phone',
        ),
    ]
