# Generated by Django 3.0.2 on 2020-02-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amsmain', '0003_auto_20200212_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regist',
        ),
    ]
